# Generated by Django 3.2.9 on 2022-05-07 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gitupper', '0002_repoevent_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reposubmission',
            name='submission',
            field=models.ForeignKey(limit_choices_to={'model__in': ['HackerSubmission', 'LeetSubmission', 'BeeSubmission']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
