# Generated by Django 3.2.9 on 2022-05-07 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gitupper', '0003_alter_reposubmission_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reposubmission',
            name='id',
        ),
        migrations.AlterField(
            model_name='reposubmission',
            name='object_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reposubmission',
            name='submission',
            field=models.ForeignKey(limit_choices_to={'model__in': ['beesubmission', 'hackersubmission', 'leetsubmission']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
