# Generated by Django 4.1.5 on 2023-01-08 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gitupper', '0006_submissiontracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissiontracker',
            name='last_submission_datetime',
        ),
        migrations.RemoveField(
            model_name='submissiontracker',
            name='last_submission_id',
        ),
        migrations.AddField(
            model_name='submissiontracker',
            name='last_submission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissiontracker',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
