# Generated by Django 4.1.5 on 2023-01-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitupper', '0007_remove_submissiontracker_last_submission_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beeuser',
            name='token_expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hackeruser',
            name='token_expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='leetuser',
            name='token_expires',
            field=models.DateTimeField(null=True),
        ),
    ]
