# Generated by Django 4.1.5 on 2023-01-18 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitupper', '0008_beeuser_token_expires_hackeruser_token_expires_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('github_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('github_email', models.EmailField(max_length=100, unique=True)),
                ('github_access_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='github_id',
        ),
        migrations.AddField(
            model_name='user',
            name='github_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gitupper.githubuser'),
        ),
        migrations.AlterField(
            model_name='repocomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitupper.githubuser'),
        ),
        migrations.AlterField(
            model_name='repocommentreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitupper.githubuser'),
        ),
        migrations.AlterField(
            model_name='repoevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitupper.githubuser'),
        ),
        migrations.AlterField(
            model_name='repoeventreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitupper.githubuser'),
        ),
    ]
