# Generated by Django 4.1.5 on 2023-01-18 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitupper', '0009_githubuser_remove_user_github_id_user_github_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gitupper.githubuser'),
        ),
    ]
