# Generated by Django 4.1.5 on 2023-01-22 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitupper', '0010_alter_user_github_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gitupper.githubuser'),
        ),
    ]
