# Generated by Django 4.1.5 on 2023-03-09 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitupper', '0012_remove_user_bee_id_remove_user_hacker_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiontracker',
            name='gitupper_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='submissiontracker',
            constraint=models.UniqueConstraint(fields=('gitupper_user', 'platform_prefix'), name='unique_user_platform'),
        ),
    ]
